# Generated by Django 4.1.3 on 2022-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lunettes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=600)),
                ("prix", models.IntegerField(default=0)),
                ("en_reduction", models.BooleanField(default=False)),
            ],
        ),
    ]
