# Generated by Django 4.1.3 on 2022-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunettes",
            name="image",
            field=models.ImageField(
                blank=True,
                db_column="image",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
